### PR TITLE
reimplement SplitHostPort so it actually validates the parts

### PR DESCRIPTION
**Pull request by amery**
port is optional, but if present it needs to be a valid u16

I'm not sure if I'm overcomplicating it though

### CODE REVIEW

**Comment by amery** [comment]
would this make it better or worse?
```diff
diff --git a/splithostport.go b/splithostport.go
index 00495db..c74efa9 100644
--- a/splithostport.go
+++ b/splithostport.go
@@ -22,7 +22,7 @@ func SplitHostPort(hostport string) (host, port string, err error) {
 
        if hostport == "" {
                // empty
-               err = addrErr(hostport, "invalid address")
+               goto invalid
        } else if hostport[0] == '[' {
                // [host]:port [host]
                host, port, err = splitHostPortBracketed(hostport)
@@ -36,7 +36,7 @@ func SplitHostPort(hostport string) (host, port string, err error) {
                        return hostport, "", nil
                }
 
-               err = addrErr(hostport, "invalid address")
+               goto invalid
        }
 
        if err != nil {
@@ -49,12 +49,13 @@ func SplitHostPort(hostport string) (host, port string, err error) {
        }
 
        if !validIP(host) && !validName(host) {
-               err = addrErr(hostport, "invalid address")
-               goto fail
+               goto invalid
        }
 
        return host, port, nil
 
+invalid:
+       err = addrErr(hostport, "invalid address")
 fail:
        return "", "", err
 }
```

**Comment by amery** [comment]
amended due to logic error in `validIPv6`

**Comment by amery** [comment]
should `host:` be considered invalid? @karasz

**Comment by amery** [comment]
@karasz dropped the `goto`, give better errors, and fail when there is nothing after the colon

**Comment by karasz** [comment]
> should `"host:"` be considered invalid? @karasz

definitely

**Review by karasz — APPROVED** [review]
+1

**Comment by amery** [comment]
`v0.6.4` tagged

**Pull request merged**
