### PR TITLE
slices: introduce SliceMap()

### PR DESCRIPTION
**Pull request by amery**
to produce a slice of one type, form a slice of another type

### CODE REVIEW

**Comment by amery** [comment]
I wonder if the callback should receive the out slice as argument so it can check for uniqueness if wanted like SliceCopyFn and SliceReplaceFn do

**Comment by amery** [comment]
```go
func(partial []T2, v T1) []T2
```

**Comment by amery** [comment]
amended as described

**Review by karasz — APPROVED** [review]
LGTM

**Comment by amery** [comment]
`v0.14.1` tagged

**Pull request merged**
