### PR TITLE
add standard constraints and SliceCopy() to drop golang.org/x/exp dependency

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Comment by amery** [comment]
Should it be SliceCopy() instead of SliceClone() for consistency with other SliceFoo/SliceFooFn functions?

**Comment by amery** [comment]
`SliceClone()` renamed to `SliceCloneFn()` and improved `SliceReplaceFn()` to survive a nil filter.

**Comment by amery** [comment]
@karasz `SliceCopyFn()` description amended.

**Review by karasz — APPROVED** [review]
LGTM

**Comment by amery** [comment]
`darvaza.org/core@v0.14.0` tagged

**Pull request merged**
