### PR TITLE
generics: ListContains, ListForEach, ListForEachElement

### PR DESCRIPTION
**Pull request by amery**
not sure If I'm crossing a boundary with the MapList helpers

### CODE REVIEW

**Review by karasz — COMMENTED** [review]
The list part is a go from me, For the Map part I am not sure, maybe we can add the core/x/ package and promote from it when it is necessary?

**Comment by amery** [comment]
@karasz PR amended to only include ListContains and ListForEach

**Review by karasz — APPROVED** [review]
LGTM, I am waiting for core/x/ as I see use for those functions too in the future.

**Comment by amery** [comment]
`v0.1.2` tagged

**Pull request merged**
