### PR TITLE
introduce SplitAddrPort() variant of SplitHostPort()

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Comment by amery** [comment]
reduced code duplication

**Review by karasz — CHANGES_REQUESTED** [review]
LGTM, but please add test cases

**Comment by amery** [comment]
tests added

**Comment by amery** [comment]
> LGTM, but please add test cases

I thought I could get away with it because it uses the same mechanisms as the other, but added tests now

**Review by karasz — APPROVED** [review]
_..._
      .'     '.
     / \     / \
    (  |     |  )
    (`"`  "  `"`)
     \         /
      \  ___  /
       '.___.'

**Comment by amery** [comment]
`v0.10.1` tagged

**Pull request merged**
