### PR TITLE
errors: Temporary and Timeout error factories and checkers

### PR DESCRIPTION
**Pull request by amery**
### **User description**
* IsTimeout() and CheckIsTimeout()
* IsTemporary() and CheckIsTemporary()
* NewTemporaryError() and NewTimeoutError()

___

### **PR Type**
enhancement, documentation

___

### **Description**
- Introduced `TemporaryError` struct to represent temporary and timeout errors.
- Added methods `IsTemporary`, `IsTimeout`, `Temporary`, and `Timeout` to `TemporaryError`.
- Implemented `NewTimeoutError` and `NewTemporaryError` functions to create specific error instances.
- Added `CheckIsTemporary` and `IsTemporary` functions to check for temporary errors without and with unwrapping, respectively.
- Added `CheckIsTimeout` and `IsTimeout` functions to check for timeout errors without and with unwrapping, respectively.
- Updated README to document the new error handling functions and types.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>errors.go</strong><dd><code>Introduce new error types and checkers for temporary and timeout </code><br><code>errors.</code></dd></summary>
<hr>
      
errors.go

<li>Introduced <code>TemporaryError</code> struct with methods <code>IsTemporary</code>, <code>IsTimeout</code>, <br><code>Temporary</code>, and <code>Timeout</code>.<br> <li> Added functions <code>NewTimeoutError</code> and <code>NewTemporaryError</code> to create <br>specific error types.<br> <li> Implemented <code>CheckIsTemporary</code> and <code>IsTemporary</code> functions to check for <br>temporary errors.<br> <li> Implemented <code>CheckIsTimeout</code> and <code>IsTimeout</code> functions to check for <br>timeout errors.<br>

</details>
    

  </td>
  <td><a href="https://github.com/darvaza-proxy/core/pull/56/files#diff-76a7e0e299c7417bae32d3098e71370980157fe29e68a366671491d147d40572">+113/-0</a>&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>README.md</strong><dd><code>Update README to document new error handling functions and types.</code></dd></summary>
<hr>
      
README.md

<li>Updated documentation to include new error handling functions and <br>types.<br> <li> Added entries for <code>IsTemporary</code>, <code>CheckIsTemporary</code>, <code>IsTimeout</code>, <br><code>CheckIsTimeout</code>, <code>TemporaryError</code>, <code>NewTemporaryError</code>, and <br><code>NewTimeoutError</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/darvaza-proxy/core/pull/56/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5">+3/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by amery** [comment]
> _PR-Agent was enabled for this repository. To continue using it, please link your git user with your CodiumAI identity [here](https://app.codium.ai/pr-agent)._
> 
> ## PR Code Suggestions ✨
> Category	Suggestion                                                                                                                                   	Score
> **Maintainability**	
> Simplify the `Error` method of `TemporaryError` by replacing the second `switch` statement with `if` statements
> **In the `Error` method of `TemporaryError`, the second `switch` statement can be simplified by combining the conditions.**
> 
> [errors.go [95-101]](https://github.com/darvaza-proxy/core/pull/56/files#diff-76a7e0e299c7417bae32d3098e71370980157fe29e68a366671491d147d40572R95-R101)
> 
> ```diff
> -switch {
> -    case !w.timeout:
> -        return cause
> -    case cause == "":
> -        return "time-out"
> -    default:
> -        return fmt.Sprintf("%s: %s", "time-out", cause)
> +if !w.timeout {
> +    return cause
>  }
> +if cause == "" {
> +    return "time-out"
> +}
> +return fmt.Sprintf("time-out: %s", cause)
>  
> ```
> 
> Suggestion importance[1-10]: 6
> 6

@karasz do you agree with this suggestion? ---^

**Comment by karasz** [comment]
> @karasz do you agree with this suggestion? ---^
imho the switch variant is more elegant and provides the same functionality. It might happen that somewhere the compiler gets smarter with the `if` construction (although I domn't see why would that be), but I do not think that the gain (if any) would be relevant. Obviously without a code tracing I cannot say what speed advantages one has over the other. Let's be more lelegant in this case I would say and stick with the switch.

**Review by karasz — APPROVED** [review]
Although my first gut reaction was that bundling timeouts and temporary in the `CheckIsTemporary` function was misleading after further consideration I say that maybe it is not. Timeouts are usually temporary albeit not always and if you really want to distinguish you can do a two step comparision.

**Comment by amery** [comment]
`v0.13.2` tagged

**Pull request merged**
