### PR TITLE
slices: introduce SliceUniquify working like SliceUnique but in-place

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Comment by amery** [comment]
@karasz rebased

**Review by karasz — APPROVED** [review]
Wondering about slices.Sort() followed by a slices.Compact() there you go, core.SliceUnique

**Review by karasz — APPROVED** [review]
LGTM

**Comment by amery** [comment]
> Wondering about slices.Sort() followed by a slices.Compact() there you go, core.SliceUnique

Not all types are sortable, or even comparable. That's why we have variants receiving a `eq` function

**Pull request merged**
